version: "3"

services:
  blue:
    image: sample-next-app-blue:latest
    container_name: sample-next-app-blue
    ports:
      - "2791:2791" # Blue app on port 2791
    environment:
      - NODE_ENV=production

  green:
    image: sample-next-app-green:latest
    container_name: sample-next-app-green
    ports:
      - "2791:2791" # Green app on port 2791
    environment:
      - NODE_ENV=production

  reverse-proxy:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80" # Expose reverse proxy on port 80
    depends_on:
      - blue
      - green