services:
  blue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sample-next-app-blue
    ports:
      - "2791:2791"
    environment:
      - NODE_ENV=production

  green:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sample-next-app-green
    ports:
      - "2792:2791"
    environment:
      - NODE_ENV=production

  reverse-proxy:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - blue
      - green
